#Kotlin
kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx4096M

#Gradle
org.gradle.jvmargs=-Xmx4096M -XX:MaxMetaspaceSize=1g -Dfile.encoding=UTF-8
org.gradle.java.home=/Users/debanshud/Library/Java/JavaVirtualMachines/openjdk-23.0.1/Contents/Home
ksp.useKSP2=true

#Android
android.nonTransitiveRClass=true
android.useAndroidX=true
org.gradle.configuration-cache=true